import { getSession } from "next-auth/react";
import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Login from "../components/Login";

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>LeoBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main className="flex bg-gray-100">
        {/* Left Sidebar */}
        <Sidebar />
        {/* Feed (create post & posts*/}
        {/* Right Sidebar */}
      </main>
    </div>
  );
}

// server side rendering
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session }
  };
}
